[package]
name = "diskcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.9"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }  # Added serde feature
